package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Búvárruha.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Buvarruha implements Targy
{
	
	
	public Buvarruha()
	{
		Global.out.print("Sikeresen letrehoztak egy buvarruhat. ");
	}
	
	/**
	 * Hozzáadja a búvárruhát a Játékos tárgyaihoz és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
		
		
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
			Global.out.print("Buvarruha sikeresen felveve. ");
		
		else 
			Global.out.print("A buvarruhat nem sikerult felvenni. ");
			
		
		return sikeres;
	}

	
	/**
	 * a játékost áthelyezi a kapott irányba és visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		boolean sikeres = j.athelyez(j.getSzogAmibeNez());
		
		Global.out.print("Ez egy buvarruha. ");
		if(sikeres)
			Global.out.print("Buvarruha sikeresen hasznalva. ");
		else
			Global.out.print("A buvarruhat nem sikertelenul hasznalni. ");
		
		
		return sikeres;
	}
	
	/**
	 * Visszaadja, hogy mi ez az objektum
	 */
	public String toString()
	{
		return "Buvarruha";
	}
}
