//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eszkimó.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Eszkimó extends Játékos
{
	private int testho;
	public void képesség(Jégtábla j)
	{
	}
	
	public void képesség(Jégtábla j)
	{
	}
}
