//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jelzopisztoly.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Jelzopisztoly implements Tárgy
{
	public void accept(Visitor v, Játékos j)
	{
	}
}
