//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Játékos.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public abstract class Játékos implements Frissítheto
{
	private Jégtábla aktjégtábla;
	private FelveszVisitor felveszVisitor;
	private HasználVisitor használVisitor;
	private int jelzopisztolydb;
	private int Munkadb;
	private int testho;
	private Jégtábla aktjégtábla;
	private Tárgy tárgyak;
	private Irany irányAmibeNéz: ;
	public void ásás()
	{
	}
	
	public void áthelyez()
	{
	}
	
	public void kilép(Jégtábla j)
	{
	}
	
	public void fázás(int i)
	{
	}
	
	public void frissít()
	{
	}
	
	public Irány getIrányAmibeNéz()
	{
	}
	
	public void hóvihar()
	{
	}
	
	public int getjelzopisztolydb()
	{
	}
	
	public int jelzopisztolyDarabokNövelése()
	{
	}
	
	public Jégtábla JégtáblaLekérdez()
	{
	}
	
	public abstract void képesség(Jégtábla j);
	
	public void lépés()
	{
	}
	
	public void pisztolyépít()
	{
	}
	
	public Irány setIrányAmibeNéz(Irány i)
	{
	}
	
	public void tárgyfelvétel()
	{
	}
	
	public void testhoNövelése(int mennyivel)
	{
	}
}
