//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jégtábla.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Jégtábla implements Frissítheto
{
	private int hó;
	private int tartóképesség;
	private Jégtábla[4] szomszédok;
	private bool vanRajtaIglu;
	private Játékos játékosok;
	private Tárgy tárgy;
	public void ásás(Jégtábla j, int i)
	{
	}
	
	public void átfordít()
	{
	}
	
	public bool ellép(Játékos j)
	{
	}
	
	public void frissít()
	{
	}
	
	public int gettartóképesség()
	{
	}
	
	public void hóNövelése()
	{
	}
	
	public void hóvihar()
	{
	}
	
	public void iglutÉpít()
	{
	}
	
	public void játékosEltávolít(Játékos j)
	{
	}
	
	public Játékos[0..10] játékosokLekérdez()
	{
	}
	
	public void rálép(Játékos j)
	{
	}
	
	public Jégtábla szomszédKérdez(Irány i)
	{
	}
	
	public void tárgyFelvesz(Játékos j)
	{
	}
	
	public bool VanRajtaIgluLekérdez()
	{
	}
}
