//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jégmezo.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Jégmezo
{
	private int hóviharCnt;
	private Frissítheto frissíthetok;
	public void hóvihar()
	{
	}
	
	public void játékvége(bool nyert)
	{
	}
	
	public void léptet()
	{
	}
	
	public void meghalt(Játékos j)
	{
	}
	
	public void setup()
	{
	}
}
