//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Visitor.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Visitor
{
	public void visit(Ásó a, Játékos j)
	{
	}
	
	public void visit(Kötél k, Játékos j)
	{
	}
	
	public void visit(Búvárruha b, Játékos j)
	{
	}
	
	public void visit(Élelem e, Játékos j)
	{
	}
	
	public void visit(Jelzopisztoly j, Játékos j)
	{
	}
}
