//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Élelem.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Élelem implements Tárgy
{
	private int pont;
	public void accept(Visitor v, Játékos j)
	{
	}
	
	public int getPont()
	{
	}
}
