package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ActionListener.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class ActionListener {
}
