package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ásó.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//


public class Aso implements Targy
{
	
	public Aso()
	{
		System.out.println("Letrehoztak egy asot");
	}
	
	/**
	 * Hozzáadja az ásót a Játékos tárgyaihoz és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
		
		System.out.println("Na most valaki megprobalta felvenni ezt az asot");
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
		{
			System.out.println("Aso sikeresen felveve");
			
		}
		else 
			System.out.println("Az asot nem sikerult felvenni");
	
		
		return sikeres;
	}

	
	/**
	 *	Az ásó használ tevékenységét valósítja meg. Csökkenti a a hó mennyiségét 2-vel annak
	 *Jégtáblának,ami abba az irányba van, amibe a Játékos, aki az ásót használja, néz. Es visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		
		System.out.println("Na most valaki megprobalta hasznalni ezt az asot");
		Irany i = j.getIranyAmibeNez();
		Jegtabla jt = j.JegtablaLekerdez();
		Jegtabla szJegtabla = jt.szomszedKerdez(i);
		
		boolean sikeres = szJegtabla.asas(2);
		
		if(sikeres)
			System.out.println("Aso sikeresen hasznalva");
		else
			System.out.println("Aso sikertelenul hasznalva");
		
		
		return sikeres;
	}
	
	
	public String Tipus()
	{
		return "Aso";
	}
}
