package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ásó.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//


public class Aso implements Targy
{
	public void accept(Visitor v, Jatekos j)
	{
	}
}
