package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ásó.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//


public class Aso implements Targy
{
	
	public Aso()
	{
		Global.out.print("Aso sikeresen letrehozva. ");
	}
	
	/**
	 * Hozzáadja az ásót a Játékos tárgyaihoz és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
		
		
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
		{
			Global.out.print("Aso sikeresen felveve. ");
			
		}
		else 
			Global.out.print("Az asot nem sikerult felvenni. ");
	
		
		return sikeres;
	}

	
	/**
	 *	Az ásó használ tevékenységét valósítja meg. Csökkenti a a hó mennyiségét 2-vel annak
	 *Jégtáblának,ami abba az irányba van, amibe a Játékos, aki az ásót használja, néz. Es visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		
		
		//int szog = j.getSzogAmibeNez();
		Jegtabla jt = j.JegtablaLekerdez();
		//Jegtabla szJegtabla = jt.szomszedKerdez(szog);
		
		Global.out.print("Ez egy aso. ");
		
		boolean sikeres = jt.asas(2);
		
		if(sikeres)
			Global.out.print("Aso sikeresen hasznalva. ");
		else
			Global.out.print("Aso sikertelenul hasznalva. ");
		
		
		return sikeres;
	}
	
	
	/**
	 * Visszaadja, hogy mi ez az objektum
	 */
	public String toString()
	{
		return "Aso";
	}
}
