package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Búvárruha.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Buvarruha implements Targy
{
	
	
	public Buvarruha()
	{
		System.out.println("Letrehoztak egy buvarruhat");
	}
	
	/**
	 * Hozzáadja a búvárruhát a Játékos tárgyaihoz és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
		
		System.out.println("Na most valaki megprobalta felvenni ezt a buvarruhat");
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
			System.out.println("Buvarruha sikeresen felveve");
		
		else 
			System.out.println("A buvarruhat nem sikerult felvenni");
			
		
		return sikeres;
	}

	
	/**
	 * a játékost áthelyezi a kapott irányba és visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		System.out.println("Na most valaki megprobalta hasznalni ezt a buvarruhat");
		boolean sikeres = j.athelyez(j.getIranyAmibeNez());
		
		if(sikeres)
			System.out.println("Buvarruha sikeresen hasznalva");
		else
			System.out.println("A buvarruhat nem sikertelenul hasznalni");
		
		
		return sikeres;
	}
	
	public String Tipus()
	{
		return "Buvarruha";
	}
}
