package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Búvárruha.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Buvarruha implements Targy
{
	
	/* (non-Javadoc)
	 * @see Jegmezo.Targy#accept(Jegmezo.Visitor, Jegmezo.Jatekos)
	 * meghívja a felvesz visitor visit függvényét.
	 */
	public void accept(Visitor v, Jatekos j)
	{
		v.visit(this, j);
	}
	
	
}
