package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Controller.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class Controller {
	private Jatekos koronlevo;
	public void palyaLetrehoz(int eszkimodb, int sarkkutato, int tabladb, int jegesmedvedb) {
	}
	
	public void korLeptet() {
	}
	
	public void ujKor() {
	}
}
