package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawSarkkutato.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawSarkkutato extends Drawable {
	private Image sarkkutatoImage;
	public void draw(Sarkkutato s) {
	}
	
	public void setPosition(int px, int py) {
	}
}
