package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawHo.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawHo extends Drawable {
	private Image hoImage;
	public void draw(Image i) {
	}
	
	public void setPosition(int px, int py) {
	}
}
