package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawEszkimo.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawEszkimo extends Drawable {
	private Image eszkimoImage;
	public void draw(Eszkimo e) {
	}
	
	public void setPosition(int px, int py) {
	}
}
