package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawSator.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawSator extends Drawable {
	private Image satorImage;
	public void draw(Sator s) {
	}
	
	public void setPosition(int px, int py) {
	}
}
