package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawElelem.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawElelem extends Drawable {
	private Image elelemImage;
	public void draw(Elelem e) {
	}
	
	public void setPosition(int px, int py) {
	}
}
