package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Drawable.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class Drawable {
	private int positionx;
	private int positiony;
	public void draw(Object o) {
	}
	
	public void setPosition(int px, int py) {
	}
}
