package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawIglu.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawIglu extends Drawable {
	private Image igluImage;
	public void draw(Iglu i) {
	}
	
	public void setPosition(int px, int py) {
	}
}
