package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawJegtabla.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//

import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 * @author Henrik
 * A jégtábla kirajzolását valósitja meg
 */
public class DrawJegtabla extends Drawable {

	/**
	 * Betölti a jégtábla képét
	 */
	public DrawJegtabla() 
	{
		try {
			img=ImageIO.read(new File("./Jegmezo/image/ice.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * Betölti a jégtáblát
	 */
	public void draw(Graphics g) {
		
		g.drawImage(img, getPositionX()*80, getPositionY()*80, null);
	}
	
	
}
