package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawBuvarruha.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawBuvarruha extends Drawable {
	private Image buvarruhaImage;
	public void draw(buvarruha b) {
	}
	
	public void setPosition(int px, int py) {
	}
}
