package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawJegesmedve.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//

import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class DrawJegesmedve extends Drawable {

	/**
	 * Betölti a jegesmedve képét
	 */
	public DrawJegesmedve() 
	{
		try {
			img=ImageIO.read(new File("./Jegmezo/image/polar1.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * Kirajzolja a jegemedvét
	 */
	public void draw(Graphics g) {
		
		g.drawImage(img, getPositionX()*80, getPositionY()*80, null);
	}
	
	
}
