package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawBuvarruha.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//

import java.awt.Graphics;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

/**
 * @author Henrik
 * A Buvarruha kirajzolását valósitja meg
 */
public class DrawBuvarruha extends Drawable {

	
	/**
	 * Betölti a búvárruha képét
	 */
	public DrawBuvarruha() 
	{
		try 
		{
			img=ImageIO.read(new File("./Jegmezo/image/wetsuit.png")); ///TODO file beillesztes
		} catch (IOException e) 
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * Kirajzolja a búvárruhát
	 */
	public void draw(Graphics g) 
	{
		g.drawImage(img, getPositionX()*80, getPositionY()*80+40, null);
	}
	
}
