package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawEszkimo.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//

import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;


/**
 * @author Henrik
 * Az Eszkimo kirajzolását valósitja meg
 */
public class DrawEszkimo extends Drawable {


	/**
	 * Betölti az eszkimó képét
	 */
	public DrawEszkimo() 
	{
		try {
			img=ImageIO.read(new File("./Jegmezo/image/eskimo2.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * Kirajzolja az eszkimót
	 */
	public void draw(Graphics g) {
		
		g.drawImage(img, getPositionX()*80, getPositionY()*80, null);
	}
	
}
