package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawSarkkutato.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//

import java.awt.Graphics;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

/**
 * @author Henrik
 * A sarkkutató kirajzolását valósitja meg
 */
public class DrawSarkkutato extends Drawable {

	/**
	 * Betölti a sarkkutató képét
	 */
	public DrawSarkkutato() {
		try {
			img=ImageIO.read(new File("./Jegmezo/image/explorer.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * kirajzolja a sarkkutatót
	 */
	public void draw(Graphics g) {
		
		g.drawImage(img, getPositionX()*80, getPositionY()*80, null);
	}
	
}
