package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawJegesmedve.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawJegesmedve extends Drawable {
	private Image jegesmedveImage;
	public void draw(Jegesmedve j) {
	}
	
	public void setPosition(int px, int py) {
	}
}
