package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawViz.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawViz extends Drawable {
	private Image vizImage;
	public void draw(Image i) {
	}
	
	public void setPosition(int px, int py) {
	}
}
