package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawTorekenyAso.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawTorekenyAso extends Drawable {
	private Image torekenyasoImage;
	public void draw(TorekenyAso t) {
	}
	
	public void setPosition(int px, int py) {
	}
}
