package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawHo.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//

import java.awt.Graphics;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

public class DrawHo extends Drawable {

	/**
	 * Betölti a hó képét
	 */
	public DrawHo() 
	{
		try 
		{
			img=ImageIO.read(new File("./Jegmezo/image/snow.png"));
		} catch (IOException e) 
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * kirajzolja a hót
	 */
	public void draw(Graphics g) 
	{
		g.drawImage(img, getPositionX()*80, getPositionY()*80, null);
	}
	
}
