package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawJegtabla.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//

import java.awt.Graphics;

public class DrawJegtabla extends Drawable {
	private Image jegtablaImage;
	public void draw(Graphics g) {
	}
	
	public void setPosition(int px, int py) {
	}
}
