package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DrawAso.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class DrawAso extends Drawable {
	private Image asoImage;
	public void draw(Aso a) {
	}
	
	public void setPosition(int px, int py) {
	}
}
