package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Élelem.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Elelem implements Targy
{
	private int pont;
	
	/* (non-Javadoc)
	 * @see Jegmezo.Targy#accept(Jegmezo.Visitor, Jegmezo.Jatekos)
	 * meghívja a használ visitor visit függvényét.
	 */
	public void accept(Visitor v, Jatekos j)
	{
		v.visit(this, j);
	}
	
	public int getPont()
	{
		
	}
}
