package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Élelem.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Elelem implements Targy
{
	private int pont;
	

	/**
	 * Konstruktor, ami beállítja az élelem pont értékét, ami azt adja meg, hogy mennyivel növeli a testhõt, a megadott értékre
	 * @param pont - Azt adja meg mennyivel növeli a játékos testhõjét, ha használják
	 */
	public Elelem(int pont) {
		this.pont = pont;
		System.out.println("Letrehoztak, egy elelmet " + this.pont + " pontertekkel");
	}
	
	/**
	 * Hozzáadja az élelmet a Játékos tárgyaihoz és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
		System.out.println("Na most valaki megprobalta felvenni ezt az elelmet");
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
			System.out.println("Elelem sikeresen felveve");
		else 
			System.out.println("Az elelmet nem sikerult felvenni");
		
		return sikeres;
	}

	
	/**
	 * a játékos testhõjét növeli azzal, hogy megeszi, azaz felhasználja az élelmet és visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		
		System.out.println("Na most valaki megprobalta hasznalni ezt az elelmet");
		boolean sikeres = j.testhoNovelese(pont);
		
		if(sikeres) 
		{
			System.out.println("Elelem sikeresen hasznalva");
			j.targyEltavolitasa(this);
		}
		else
			System.out.println("Nem sikerult hasznalni az elelmet");
		
		
		return sikeres;
	}
	
	/**
	 * @return Visszaadja az élelem pont értékét, ami azt adja meg, hogy mennyivel növeli az étel a Játékos testhõjét 
	 */
	public int getPont()
	{
		System.out.println("Valaki az elelem pontszamat kerdezi le eppen, ami: " + pont);
		return pont;
	}
	
	
	public String Tipus()
	{
		return "Elelem";
	}
}
