package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eszkimó.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Eszkimo extends Jatekos
{
	private int testho;
	public void kepesseg(Jegtabla j)
	{
	}
	
}
