package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eszkimó.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//

import java.util.List;

public class Eszkimo extends Jatekos
{	
	/**
	 * Konstruktor, ami létrehozza a Játékost a medadott paraméterekkel
	 * @param jegmezo - a jégmezõ, amin a Játékos van
	 * @param aktjegtabla - a Jégtábla, amin a Játékos áll
	 * @param jelzopisztolydb - a Játékos jelzõpisztoly darabjainak száma
	 * @param Munkadb - A Játékos hátralévõ elvégezhetõ munka száma
	 * @param testho - a Játékos hátralévõ testhõje
	 * @param targyak - a Játékos által tárolt tárgyak
	 * @param iranyAmibeNez - az Irany, amibe a Játékos néz
	 */
	public Eszkimo(Jegmezo jegmezo,
	int Munkadb,
	int testho,
	Irany iranyAmibeNez)
	{
		super(jegmezo,
				Munkadb,
				testho,
				iranyAmibeNez);
		
		System.out.println("Letrehoztak egy Eszkimot");
	}
	/**
	 * Épít egy iglut arra Jégtáblára, amerre nez
	 */
	public void kepesseg()
	{
		System.out.println("En, az eszkimo, most megprobalok egy popec iglut epiteni");
		Iglu i = new Iglu();
		
		Jegtabla j = aktjegtabla.szomszedKerdez(iranyAmibeNez);
		if(j != null)
		{
			j.setjegtablaVedelme(i);
			
			System.out.println("Iglu epitese sikeres");
			this.MunkaDBcsokkentese(1);
		}
		else {
			System.out.println("A szomszed nem letezik"); 
			System.out.println("Iglu epitese sikertelen");
		}
		
		
	}
	
	/**
	 * Visszaadja, hogy mi ez az objektum
	 */
	public String toString()
	{
		return "Eszkimo";
	}
	
}
