package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FelveszVisitor.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class FelveszVisitor implements Visitor
{
	
	/**
	 * Hozzáadja az ásót a Játékos tárgyaihoz
	 */
	public void visit(Aso a, Jatekos j)
	{
		j.targyfelvetel(a);
		
	}
	
	public void visit(Kotel k, Jatekos j)
	{
		j.targyfelvetel(k);;
	}
	
	public void visit(Buvarruha b, Jatekos j)
	{
		j.targyfelvetel(b);
	}
	
	public void visit(Elelem e, Jatekos j)
	{
		j.targyfelvetel(e);
	}
	
	/**
	 *	Hozzáadja a jelzõpisztoly darabot a Játékoshoz 
	 */
	public void visit(Jelzopisztoly jp, Jatekos j)
	{
		j.targyfelvetel(jp);
		j.jelzopisztolyDarabokNovelese();
	}
}
