package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FelveszVisitor.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class FelveszVisitor implements Visitor
{
	public void visit(Aso a, Jatekos j)
	{
		Irany i=j.getIranyAmibeNez();
		Jegtabla jt=j.JegtablaLekerdez();
		Jegtabla szomszedos=jt.szomszedKerdez(i);
		szomszedos.asas(2);
		
	}
	
	public void visit(Kotel k, Jatekos j)
	{
	}
	
	public void visit(Buvarruha b, Jatekos j)
	{
		j.targyfelvetel(b);
	}
	
	public void visit(Elelem e, Jatekos j)
	{
		j.targyfelvetel(e);
	}
	
	public void visit(Jelzopisztoly jp, Jatekos j)
	{
	}
}
