package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Frissítheto.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public interface Frissitheto
{
	public void frissit();
	
	public void hovihar();
}
