package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Frissítheto.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//



/**
 * @author Henrik
 * A játékban lévõ Frissíthetõ objektumok interfésze
 */
public interface Frissitheto
{
	/**
	 * függvény, amit minden kör elején meghívunk és frissíti a megadott objektumot, az implementálók specifikációja szerint
	 */
	public void frissit();
	
	/**
	 * függvény, amit hóviharkor hívunk meg. Elvégzi a hóviharkor teendõket, az implementálók specifikációja szerint
	 */
	public void hovihar();
}
