package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GombokActionListener_.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class GombokActionListener_ implements ActionListener {
	public void ActionPerformed(ActionEvent ae) {
	}
}
