package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HasználVisitor.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class HasznalVisitor implements Visitor
{
	public void visit(Aso a, Jatekos j)
	{
	}
	
	public void visit(Kotel k, Jatekos j)
	{
	}
	
	public void visit(Buvarruha b, Jatekos j)
	{
	}
	
	public void visit(Elelem e, Jatekos j)
	{
	}
	
	public void visit(Jelzopisztoly jp, Jatekos j)
	{
	}
}
