package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Játékos.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//

import java.util.List;

public abstract class Jatekos implements Frissitheto
{
	protected Jegtabla aktjegtabla;
	private FelveszVisitor felveszVisitor;
	private HasznalVisitor hasznalVisitor;
	private int jelzopisztolydb;
	protected int Munkadb;
	private int testho;
	private List<Targy> targyak;
	protected Irany iranyAmibeNez;
	
	
	/**
	 * Konstruktor, ami létrehozza a Játékost a medadott paraméterekkel
	 * @param aktjegtabla - a Jégtábla, amin a Játékos áll
	 * @param felveszVisitor - a Játékos felvesz tevékenységét kezelõ visitor
	 * @param hasznalVisitor - a Játékos hasznal tevékenységét kezelõ visitor
	 * @param jelzopisztolydb - a Játékos jelzõpisztoly darabjainak száma
	 * @param Munkadb - A Játékos hátralévõ elvégezhetõ munka száma
	 * @param testho - a Játékos hátralévõ testhõje
	 * @param targyak - a Játékos által tárolt tárgyak
	 * @param iranyAmibeNez - az Irany, amibe a Játékos néz
	 */
	public Jatekos(Jegtabla aktjegtabla,
	FelveszVisitor felveszVisitor,
	HasznalVisitor hasznalVisitor,
	int jelzopisztolydb,
	int Munkadb,
	int testho,
	List<Targy> targyak,
	Irany iranyAmibeNez)
	{
		this.aktjegtabla = aktjegtabla;
		this.felveszVisitor = felveszVisitor;
		this.hasznalVisitor = hasznalVisitor;
		this.jelzopisztolydb = jelzopisztolydb;
		this.Munkadb = Munkadb;
		this.testho = testho;
		this.targyak = targyak;
		this.iranyAmibeNez = iranyAmibeNez;
	}
	
	
	/**
	 * A Játékos ás 1-et azon a Jégtáblán, amin áll
	 */
	public void asas()
	{
		
		boolean sikeres = aktjegtabla.asas(1);
		if(sikeres)
		{
			Munkadb--;
			System.out.println("Asas sikeresen elvegezve");
		}
		else
			System.out.println("Asas sikertelenul elvegezve");
		
	}
	
	/**
	 * @param i i irányban lévõ szomszédos jégmezõre helyezi át a játékost.
	 */
	public void athelyez(Irany i)
	{
		Jegtabla szomszed=aktjegtabla.szomszedKerdez(i);
		if (szomszed!=null) {
			aktjegtabla=szomszed;
			System.out.println("Sikeresen athelyezve");
		}
		else 
			System.out.println("Nem sikerult athelyezni");
	}
	
	public void kilep(Jegtabla j)
	{
	}
	
	/**
	 * @param i csökkenti a testhõt a megadott mennyiséggel
	 */
	public void fazas(int i)
	{
		testho-=i;
		System.out.println("Testho csokkentve");
	}
	
	public void frissit()
	{
	}
	
	/**
	 * @return Visszaadja a Játékos iranyAmibeNez-ét
	 */
	public Irany getIranyAmibeNez()
	{
		return iranyAmibeNez;
	}
	
	
	/**
	 * ha nincs iglu a jégtáblán ahol van, akkor meghívja a fázás függvényt, ha a testhõje 0-ra 
	 * csökken meghal, ezt jelzi a jégmezõnek
	 */
	public void hovihar()
	{
		boolean iglu=aktjegtabla.VanRajtaIgluLekerdez();
		if(!iglu) {
			this.fazas(1);
		}
		if(testho==0) {
			jm.meghalt();
		}
	}
	
	/**
	 * @return Visszaadja a Játékos által tárolt jelzõpisztoly darabok számát
	 */
	public int getjelzopisztolydb()
	{
		return jelzopisztolydb;
	}
	
	/**
	 * Növeli eggyel a jelzopisztolydb-t.
	 */
	public void jelzopisztolyDarabokNovelese()
	{
		jelzopisztolydb++;
	}
	
	public Jegtabla JegtablaLekerdez()
	{
		return aktjegtabla;
	}
	
	/**
	 * A játékos képessége, amit a leszármazottak valósítanak meg
	 * @param j - a jégtábla, amin a képességet végezzük
	 */
	public abstract void kepesseg(Jegtabla j);
	
	public void lepes()
	{
	}
	
	public void pisztolyepit()
	{
	}
	
	/**
	 * Beállítja a játékost, hogy abba az irányba nézzen, amit megadunk
	 * @param i - Az irány, amibe szeretnénk, hogy nézzen a Játékos
	 */
	public void setIranyAmibeNez(Irany i)
	{
		iranyAmibeNez = i;
	}
	
	
	public void targyfelvetel(Targy t)
	{
		int i=targyak.size();
		targyak.add(t);
		int j=targyak.size();
		if (i==j) {
			System.out.println("Targy hozzaadva");
		}
		else 
			System.out.println("Nem sikerult felvenni a targyat");
	}
	
	public void testhoNovelese(int mennyivel)
	{
		
		testho+= mennyivel;
		System.out.println("Testho novelve");
	}
}
