package Jegmezo;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jégmezo.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//





public class Jegmezo
{
	private int hoviharCnt;
	private List<Frissitheto> frissithetok;
	
	/**
	 * a konstruktor, ami létrehozza a Jégezõt
	 * @param hoviharCnt - kezdetben hány kör van a hóviharig
	 * @param frissithetok - a jégmezõn található frissíthetõk
	 */
	public Jegmezo(int hoviharCnt,
	List<Frissitheto> frissithetok)
	{
		this.hoviharCnt = hoviharCnt;
		this.frissithetok = frissithetok;
	}
	
	public void hovihar()
	{
	}
	
	
	/**
	 * @param nyert  ha igaz értéket kap nyertünk, ha hamisat vesztettünk, a játéknak vége.
	 */
	public void jatekvege(boolean nyert)
	{
		if(!nyert) 
			System.out.println("Sajnos vesztettetek.");
		else 
			System.out.println("Nyertetetek!");
	}
	
	/**
	 * A frisiíthetõket frissíti, és ha a hóvihar számáló nullára vált meghívja a hóvihar függvényét 
	 * a frisiíthetõknek. És visszaállítja a hóvihar számálót
	 */
	public void leptet()
	{
		hoviharCnt--;
		for(int i=0;i<frissithetok.size();i++) {
			frissithetok.get(i).frissit();
			if(hoviharCnt==0)
			{
				frissithetok.get(i).hovihar();
				hoviharCnt = 99;
			}
		}
	}
	
	/**
	 * @param j ha meghalt egy játékos vége a játéknak, meghívja ezt a függvényt false értékkel
	 */
	public void meghalt(Jatekos j)
	{
		this.jatekvege(false);
	}
	
	public void setup()
	{
	}
}
