package Jegmezo;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jégmezo.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//





public class Jegmezo
{
	/**
	 * Azt adja meg, hogy hány kör van a következõ hóviharig
	 */
	private int hoviharCnt;
	
	/**
	 * A jégmezõn lévõ frissíthetõk
	 */
	private List<Frissitheto> frissithetok;
	
	/**
	 * A jégmezõn lévõ játékosok
	 */
	private List<Jatekos> jatekosok;
	
	/**
	 * Azt tárolja, hogy véget ért-e a játék
	 */
	private boolean VegeAjateknak;
	
	/**
	 * Azt tárolja, hogy a játék elsõ köre megy-e
	 */
	private boolean elsoKor;
	
	/**
	 * a konstruktor, ami létrehozza a Jégezõt a megadott paraméterekkel 
	 * @param hoviharCnt - kezdetben hány kör van a hóviharig
	 */
	public Jegmezo(int hoviharCnt)
	{
		this.hoviharCnt = hoviharCnt;
		frissithetok = new ArrayList<>();
		jatekosok = new ArrayList<>();
		VegeAjateknak = false;
		elsoKor = true;
		Global.out.print("Sikeresen letrehoztak egy jegmezot. Hovihar: "+hoviharCnt
				+" mulva lesz. ");
	}
	
	/**
	 * Felveszi a frissithetok közé a paraméterben megadott frissithetot
	 * @param f - a frissíthetõ, amit fel akarunk venni
	 */
	public void addFrissitheto(Frissitheto f)
	{
		
		frissithetok.add(f);
		Global.out.print("Sikeresen hozzáadva a jégmezõhöz az új frissithetõ. ");
		
	}
	
	
	/**
	 * Felveszi a jatekosok koze a paraméterben megadott jatekost
	 * @param j - a jatekos, akit fel akarunk venni
	 */
	public void addJatekos(Jatekos j)
	{
		
		jatekosok.add(j);
		Global.out.print("Jatekos sikeresen hozzáadva a jégmezõhöz. ");
		
	}
	

	
	
	/**
	 * @param nyert  ha igaz értéket kap nyertünk, ha hamisat vesztettünk, a játéknak vége.
	 */
	public void jatekvege(boolean nyert)
	{
		Global.out.print("Vege a jateknak. ");
		if(!nyert) 
			Global.out.print("Sajnos vesztettetek. ");
		else 
			Global.out.print("Nyertetetek! ");
		VegeAjateknak = true;
	}
	
	/**
	 * A frisiíthetõket frissíti, és ha a hóvihar számáló nullára vált meghívja a hóvihar függvényét 
	 * a frisiíthetõknek. És visszaállítja a hóvihar számálót
	 */
	public void leptet()
	{
		
			if(!elsoKor)
			{
				Global.out.print("Uj kor kezdodott. ");
				hoviharCnt--;
				
				
				if(hoviharCnt==0)
				{	
					for(int i=0;i<frissithetok.size();i++) 
						frissithetok.get(i).hovihar();
				} 
				for(int i=0;i<frissithetok.size();i++) {
					frissithetok.get(i).frissit();
				}
				
				Random r=new Random();
				if(hoviharCnt==0)hoviharCnt = r.nextInt(5)+1;
			}
			else
				elsoKor = false;
			
			Global.out.print("Jegmezo: az ujabb hoviharig " + hoviharCnt + "db kor van hatra. ");
		
	}
	
	/**
	 * @param j ha meghalt egy játékos vége a játéknak, meghívja ezt a függvényt false értékkel
	 */
	public void meghalt(Jatekos j)
	{
		Global.out.print("Egy jatekos meghalt. ");
		this.jatekvege(false);
	}
	
	
	/**
	 * Megkonstruálja a jégmezõt a megadott paraméterekkel
	 * @param jegtablakSzamaSzelteben - hány jégtáblát tároljon a jégmezõ a vízszintes síkon
	 * @param jegtablakSzamaHosszaban - hány jégtáblát tároljon a jégmezõ a függõleges síkon
	 * @param eszkimokSzama - azt adja meg, hogy hány eszkimó legyen a jégemezõn, a sarrkkutatokSzama-val együtt nem haladhatja meg a tízet 
	 * @param sarrkkutatokSzama - azt adja meg, hogy hány sarkkutató legyen a jégemezõn, a eszkimokSzama-val együtt nem haladhatja meg a tízet 
	 */
	public void setup( int jegtablakSzamaSzelteben, int jegtablakSzamaHosszaban, int eszkimokSzama, int sarrkkutatokSzama)
	{
		
		Jegtabla jgk[][] = new Jegtabla[jegtablakSzamaHosszaban][jegtablakSzamaSzelteben];
		
		//incializaljuk a jegtablakat
		for(int i = 0; i < jegtablakSzamaHosszaban; i++)
		{
			for(int j = 0; j < jegtablakSzamaSzelteben; j++)
			{
				jgk[i][j] = new Jegtabla(this, false, 5, 2, 4); // TODO: itt majd randomizalni kell a homennyiseget, tartokepesseget es a targyat
			}
		}
		
		//ujra bejarjuk es beallitjuk a szomszedokat
		for(int i = 0; i < jegtablakSzamaHosszaban; i++)
		{
			for(int j = 0; j < jegtablakSzamaSzelteben; j++)
			{
					Jegtabla sz0 = j + 1 < jegtablakSzamaSzelteben? jgk[i][j + 1] : null;
					Jegtabla sz1 = j - 1 >= 0? jgk[i][j - 1] : null;
					Jegtabla sz2 = i - 1 >= 0? jgk[i - 1][j] : null;
					Jegtabla sz3 = i + 1 < jegtablakSzamaHosszaban? jgk[i + 1][j] : null;
					jgk[i][j].setSzomszed(sz0,0, 0);
					jgk[i][j].setSzomszed(sz1,1,180);
					jgk[i][j].setSzomszed(sz2, 2,90);
					jgk[i][j].setSzomszed(sz3, 3,270);
			}
		}
		
		Random r  = new Random();
		for(int i = 0; i < eszkimokSzama; i++)
		{
			Eszkimo e = new Eszkimo(this, 4, 5);
			
			jgk[r.nextInt(jegtablakSzamaHosszaban)][r.nextInt(jegtablakSzamaSzelteben)].addJatekos(e);
			
		}
		
		for(int i = 0; i < sarrkkutatokSzama; i++)
		{
			Sarkkutato sk = new Sarkkutato(this, 4, 4);
			jgk[r.nextInt(jegtablakSzamaHosszaban)][r.nextInt(jegtablakSzamaSzelteben)].addJatekos(sk);
		}
		
		Global.out.print("Jatek sikeresen letrehozva. ");
	}
	
	/**
	 * Visszaadja, hogy mi ez az objektum
	 */
	public String toString()
	{
		return "Jegmezo";
	}
	
	/**
	 * @return Visszaadja a hoviharCnt attribútumot
	 */
	public int getHoviharCnt()
	{
		return hoviharCnt;
	}
	
	/**
	 * @return Visszaadja a jégemzõn lévõ játékosok számát
	 */
	public int GetJatekosSzam()
	{
		return jatekosok.size();
	}
	
	
	/**
	 * @return Visszaadja a jégemzõn lévõ játékosok listáját
	 */
	public List<Jatekos> getJatekosok(){
		return jatekosok;
	}
	
	/**
	 * @return Visszaadja, hogy véget ért-e a játék
	 */
	public boolean getJatekvege(){
		return VegeAjateknak;
	}
}
