package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jégtábla.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//

import java.util.List;

public class Jegtabla implements Frissitheto
{
	private int ho;
	private int tartokepesseg;
	private List<Jegtabla> szomszedok;
	private boolean vanRajtaIglu;
	private List<Jatekos> jatekosok;
	private Targy targy;
	
	
	/**
	 * Csökkenti a Jégtábla hó mennyiségét i-vel, ha nulla alá megy a hó, akkor -1-re állítjuk a hómennyiséget és a rajta lévõ tárgyat kiásottnak tekintjük.
	 * Ha -1 vagy az alatti a hó mennyiség nem történik semmi
	 * @param i - A mennyiség, amivel a havat csökkenteni szeretnénk
	 * @return Visszaadja, hogy történt-e ásás
	 */
	public boolean asas(int i)
	{
		if(ho >= 0)
		{
			ho -= i;
			if(ho < -1)
				ho = -1;
			
			return true;
		}
		else
			return false;
		
	}
	
	public void atfordit()
	{
	}
	
	public boolean ellep(Jatekos j)
	{
	}
	
	public void frissit()
	{
	}
	
	/**
	 * @return Visszaadja, hogy hány játékost bír el a Jégtábla
	 */
	public int gettartokepesseg()
	{
		return tartokepesseg;
	}
	
	/**
	 * növeli a havat a jégtáblán
	 */
	public void hoNovelese()
	{
		ho++;
		System.out.println("Ho mennyisege megnovelve");
	}
	
	
	/**
	 *meghívja a honoveles fügvényt
	 */
	public void hovihar()
	{
		this.hoNovelese();
	}
	
	/**
	 * Épít egy iglut magára, ha már nincs rajta egy iglu
	 * @return Visszatér azzal, hogy építetet-e iglut magára
	 */
	public boolean iglutEpit()
	{
		if(vanRajtaIglu)
			return false;
		else
		{
			vanRajtaIglu = true;
			return true;
		}
	}
	
	public void jatekosEltavolit(Jatekos j)
	{
	}
	
	public List<Jatekos> jatekosokLekerdez()
	{
		return jatekosok;
	}
	
	public void ralep(Jatekos j)
	{
	}
	
	/**
	 * @param i
	 * @return visszaadja az i irányban lévõ szomszédot
	 */
	public Jegtabla szomszedKerdez(Irany i)
	{
		return szomszedok.get(i);
	}
	
	
	/**
	 * Meghívja a rajtalévõ tárgy felvesz függvényét, ha a hó rajta -1
	 * @param j - a Játékos, aki fel akarja venni a tárgyat
	 * @return Visszaadja, hogy sikeres volt-e a tárgyfelvétel
	 */
	public boolean targyFelvesz(Jatekos j)
	{
		if(ho == -1)
		{
			if(targy != null)
			{
				boolean sikeres =  targy.felvesz(j);
				if(sikeres)
				{
					System.out.println("A jegtablarol valo targy felvetel sikeres volt");
					targy = null; // töröljük a tárgyat a tábláról
				}
				
				else 
					System.out.println("A jegtablarol valo targy felvetel nem volt sikeres");
				
				
				return sikeres;
			}
			else
			{
				System.out.println("A jegtablan nincs targy");
				return false;
			}
		
		}
		else
		{
			System.out.println("A jegtablan levo targyat meg ho takarja");
			return false;
		}
	}
	
	/**
	 * @return visszaadja, hogy van e iglu a jégtáblán
	 */
	public boolean VanRajtaIgluLekerdez()
	{
		return vanRajtaIglu;
	}
}
