package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jégtábla.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//

import java.util.List;

public class Jegtabla implements Frissitheto
{
	private int ho;
	private int tartokepesseg;
	private List<Jegtabla> szomszedok;
	private boolean vanRajtaIglu;
	private Jatekos jatekosok;
	private Targy targy;
	public void asas(Jegtabla j, int i)
	{
	}
	
	public void atfordit()
	{
	}
	
	public boolean ellep(Jatekos j)
	{
	}
	
	public void frissit()
	{
	}
	
	public int gettartokepesseg()
	{
	}
	
	public void hoNovelese()
	{
	}
	
	public void hovihar()
	{
	}
	
	public void iglutEpit()
	{
	}
	
	public void jatekosEltavolit(Jatekos j)
	{
	}
	
	public List<Jatekos> jatekosokLekerdez()
	{
	}
	
	public void ralep(Jatekos j)
	{
	}
	
	public Jegtabla szomszedKerdez(Irany i)
	{
	}
	
	public void targyFelvesz(Jatekos j)
	{
	}
	
	public boolean VanRajtaIgluLekerdez()
	{
	}
}
