package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jelzopisztoly.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//

import java.util.List;

public class Jelzopisztoly implements Targy
{
	
	public Jelzopisztoly()
	{
		System.out.println("Letrehoztak egy jelzopisztolyt");
	}
	
	/**
	 *	Hozzáadja a jelzõpisztoly darabot a Játékoshoz és növeli a jelzõpisztoly darabjainak a számát és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
	
		System.out.println("Jelzopisztoly: megprobalnak felvenni");
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
		{
			System.out.println("Jelzopisztoly sikeresen felveve");
			j.jelzopisztolyDarabokNovelese();
		}
		else 
			System.out.println("A jelzopisztolyt nem sikerult felvenni");	
		
		return sikeres;
	}

	/**
	 *	A jelzõpisztoly használ tevékenységét valósítja meg. Megpróbálja összeszerelni a jelzõpisztoly és és visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		
		System.out.println("Jelzopisztoly: megprobalnak hasznalni");
		System.out.println("Jelzopisztoly: ezert lekerdezem a jatekosnak, aki engem hasznal a jelzopisztolyDB-jait");
		int jelzopisztolyDB = j.getjelzopisztolydb();
		System.out.println("Jelzopisztoly: ezert lekerdezem a jatekos jegtablajan levo jatekosokat");
		List<Jatekos> jatekosok = j.JegtablaLekerdez().jatekosokLekerdez();
		
		for(int i = 0; i < jatekosok.size(); i++)
		{
			System.out.println("Jelzopisztoly: most lekerdezem a jatekosok jelzopisztoly darabjait");
			jelzopisztolyDB += jatekosok.get(i).getjelzopisztolydb();
		}
		
		if(jelzopisztolyDB >= 3)
		{
			System.out.println("Sikeres összeszerelés (pew pew)");
			j.getJegmezo().jatekvege(true);
			return true;
		}
		else
		{
			System.out.println("Sikertelen összeszerelés :/");
			return false;
		}
	}
	
	public String Tipus()
	{
		return "Jelzopisztoly";
	}
}
