package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jelzopisztoly.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//

import java.util.List;

/**
 * @author Henrik
 * A játékban lévõ Jelzõpisztoly darabokat reprezentálja
 */
public class Jelzopisztoly implements Targy
{
	
	/**
	 * Létrehozza a jelzõpisztolyt
	 */
	public Jelzopisztoly()
	{
		Global.out.print("Sikeresen letrehoztak egy jelzopisztolyt. ");
	}
	
	/**
	 *	Hozzáadja a jelzõpisztoly darabot a Játékoshoz és növeli a jelzõpisztoly darabjainak a számát és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
	
		
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
		{
			Global.out.print("Jelzopisztoly sikeresen felveve. ");
			j.jelzopisztolyDarabokNovelese();
		}
		else 
			Global.out.print("A jelzopisztolyt nem sikerult felvenni. ");	
		
		return sikeres;
	}

	/**
	 *	A jelzõpisztoly használ tevékenységét valósítja meg. Megpróbálja összeszerelni a jelzõpisztoly és és visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		
		Global.out.print("Ez egy jelzopisztoly. ");
		int jelzopisztolyDB = 0;
		
		List<Jatekos> jatekosok = j.JegtablaLekerdez().jatekosokLekerdez();
		
		for(int i = 0; i < jatekosok.size(); i++)
		{
			
			jelzopisztolyDB += jatekosok.get(i).getjelzopisztolydb();
		}
		Global.out.print("JelzopisztolyDB-ok szama: "+jelzopisztolyDB+". ");
		if(jelzopisztolyDB >= 3)
		{
			Global.out.print("Sikeres összeszerelés (pew pew). ");
			j.getJegmezo().jatekvege(true);
			return true;
		}
		else
		{
			Global.out.print("Sikertelen összeszerelés :/. ");
			return false;
		}
	}
	
	/**
	 * Visszaadja, hogy mi ez az objektum
	 */
	public String toString()
	{
		return "Jelzopisztoly";
	}
}
