package Jegmezo;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Kötél.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//


public class Kotel implements Targy
{
	public Kotel()
	{
		System.out.println("Letrehoztak egy kotelet");
	}
	
	/**
	 * Hozzáadja a kötelet a Játékos tárgyaihoz és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
		
		System.out.println("Kotel: most meprobalnak felvenni");
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
		{
			System.out.println("Kotel sikeresen felveve");
		}
		else 
			System.out.println("A Kotelet nem sikerult felvenni");	
		
		return sikeres;
	}

	
	/**
	 * Lekérdezi az irányt, amibenéz, majd lekéri a szomszédosjégtáblát és   
	 * elkezd végig menni a játékosok listáján, aki ott van és áthelyezi õket és visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		
		System.out.println("Kotel: most meprobalnak hasznalni");
		
		System.out.println("Kotel: most lekerdezem a jatekos iranyAmibeNezet");
		int szog = j.getSzogAmibeNez();
		System.out.println("Kotel: most lekerdezem a jatekos jegtablajat");
		Jegtabla jt = j.JegtablaLekerdez();
		
		System.out.println("Kotel: most lekerdezem a jegtabla, a jatekos iranyAmibeNez fele levo szomszedjat");
		Jegtabla szJegtabla = jt.szomszedKerdez(szog);
		
		if(szJegtabla != null) {
			System.out.println("Kotel: Letezik a szomszed, szoval rola az osszes jatekost athuzom a jatekos,aki hasznal jegtablajara");
			List<Jatekos> jatekos = szJegtabla.jatekosokLekerdez();
			for(int jsz = 0; jsz < jatekos.size(); jsz++) {
				System.out.println("Kotel: Epp athuzok egy jatekost a masik tablara");
				jatekos.get(jsz).athelyez(SzogKezelo.szogTukrozveAzOrigora(szog));
			}
			return true;
		}
		else {
			System.out.println("Kotel: nem letezik a szomszed, ezert nem lehet jatekosokat athuzni rola");
			return false;
		}
	
		
	}
	
	/**
	 * Visszaadja, hogy mi ez az objektum
	 */
	public String toString()
	{
		return "Kotel";
	}
	
}
