package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Kötél.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//


public class Kotel implements Targy
{
	
	
	/**
	 * Hozzáadja a kötelet a Játékos tárgyaihoz és visszaadja, hogy sikerült-e
	 */
	public boolean felvesz(Jatekos j) {
		boolean sikeres = j.targyHozzadasa(this);
		
		if(sikeres)
		{
			System.out.println("Kotel sikeresen felveve");
		}
		else 
			System.out.println("A Kotelet nem sikerult felvenni");	
		
		return sikeres;
	}

	
	/**
	 * Lekérdezi az irányt, amibenéz, majd lekéri a szomszédosjégtáblát és   
	 * elkezd végig menni a játékosok listáján, aki ott van és áthelyezi õket és visszaadja, hogy sikerült-e
	 */
	public boolean hasznal(Jatekos j) {
		Jegtabla jt = j.JegtablaLekerdez();						//Komplexitása miatt csak azt a részt tudjuk 
		boolean sikeres = false;								//tesztelni, hogy lekérdezi-e a saját jégtábláját
		if(jt != null)
			sikeres = true;
		
		if(sikeres) 
		{
			System.out.println("Kotel sikeresen hasznalva");
			j.targyEltavolitasa(this);
		}
		else
			System.out.println("Nem sikerult hasznalni a kotelet");
		
		
		return sikeres;
		
		/*Irany i = j.getIranyAmibeNez();
		Jegtabla jt = j.JegtablaLekerdez();
		Jegtabla szJegtabla = jt.szomszedKerdez(i);
		
		List<Jatekos> jatekos = szJegtabla.jatekosokLekerdez();
		for(int jsz = 0; jsz < jatekos.size(); jsz++) {
			jatekos.get(jsz).athelyez(i);
		}
		
		return true;*/
		
	}
	
	
}
