//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MenuActionListener.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class MenuActionListener implements ActionListener {
	private JTextField eszkimoTextF;
	private JTextField sarkkutatoTextF;
	private JLabel utasitasLab;
	public void ActionPerformed(ActionEvent ae) {
	}
}
