package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sarkkutató.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//

import java.util.List;

public class Sarkkutato extends Jatekos
{
	
	/**
	 * Konstruktor, ami létrehozza a Játékost a medadott paraméterekkel
	 * @param jegmezo - a jégmezõ, amin a Játékos van
	 * @param aktjegtabla - a Jégtábla, amin a Játékos áll
	 * @param jelzopisztolydb - a Játékos jelzõpisztoly darabjainak száma
	 * @param Munkadb - A Játékos hátralévõ elvégezhetõ munka száma
	 * @param testho - a Játékos hátralévõ testhõje
	 * @param targyak - a Játékos által tárolt tárgyak
	 * @param iranyAmibeNez - az Irany, amibe a Játékos néz
	 */
	public Sarkkutato(Jegmezo jegmezo,
	int jelzopisztolydb,
	int Munkadb,
	int testho,
	List<Targy> targyak,
	Irany iranyAmibeNez)
	{
		super(jegmezo,
				jelzopisztolydb,
				Munkadb,
				testho,
				targyak,
				iranyAmibeNez);
		
		System.out.println("Letrehoztak egy sarkkutatot");
	}

	
	/**
	 * A sarkutató megvizsgálja a megadott Jégtábla tartóképességét
	 */
	public void kepesseg(Jegtabla j)
	{
		System.out.println("Sarkkutato: Epp a kepessegemet akarjak hasznalni");
		System.out.println("Sarkkutato: ezert lekerdezem a jegtabla tartokepesseget");
		System.out.println("A jegtabla tartokepessege: " + j.gettartokepesseg());
		MunkaDBcsokkentese(1);
	}
	
	
	/**
	 * Visszaadja, hogy mi ez az objektum
	 */
	public String toString()
	{
		return "Sarkkutato";
	}
	
}
