package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sarkkutató.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//

import java.util.List;

public class Sarkkutato extends Jatekos
{
	
	/**
	 * A sarkkutató konstruktora, meghívja a Játékos konstuktorát
	 * @param aktjegtabla - a Jégtábla, amin a Játékos áll
	 * @param jelzopisztolydb - a Játékos jelzõpisztoly darabjainak száma
	 * @param Munkadb - A Játékos hátralévõ elvégezhetõ munka száma
	 * @param testho - a Játékos hátralévõ testhõje
	 * @param targyak - a Játékos által tárolt tárgyak
	 * @param iranyAmibeNez - az Irany, amibe a Játékos néz
	 */
	public Sarkkutato(Jegtabla aktjegtabla,
	int jelzopisztolydb,
	int Munkadb,
	int testho,
	List<Targy> targyak,
	Irany iranyAmibeNez) 
	{
		super(aktjegtabla, 
				jelzopisztolydb,
				Munkadb,
				testho,
				targyak,
				iranyAmibeNez);
	}

	
	/**
	 * A sarkutató megvizsgálja a megadott Jégtábla tartóképességét
	 */
	public void kepesseg(Jegtabla j)
	{
		System.out.println("A jegtabla tartokepessege: " + j.gettartokepesseg());
	}
	
}
