package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sarkkutató.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public class Sarkkutato extends Jatekos
{
	private int testho;
	
	public void kepesseg(Jegtabla j)
	{
	}
	
}
