package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tárgy.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public interface Targy
{
	/**
	 * @param v
	 * @param j
	 */
	public void accept(Visitor v, Jatekos j);
	
}
