package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TargyActionListener.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class TargyActionListener implements ActionListener {
	private JComboBox JCtaska;
	public void ActionPerformed(ActionEvent ae) {
	}
}
