package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tárgy.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public interface Targy
{
	/**
	 * meghívja magára a visitort  a paraméterében lévõ játékossal
	 * @param v - a Visitor amivel használni szeretnénk a Tárgyat
	 * @param j - a Játékos, aki használja a Tárgyat
	 */
	public void accept(Visitor v, Jatekos j);
	
}
