package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : View.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//




public class View {
	private JPanel jatekPanel;
	private JPanel jegmezoPanel;
	private JComboBox taska;
	private JPanel iranyPanel;
	private JButton HasznalButton;
	private JButton KepessegButton;
	private JButton BalraButton;
	private JButton JobbraButton;
	private JButton LepButton;
	public Controller view;
	public void inicializalas() {
	}
	
	public void addDrawable(Drawable d) {
	}
	
	public void setButtons() {
	}
	
	public void setPanels() {
	}
	
	public void DrawAll() {
	}
	
	public void gameWon() {
	}
	
	public void gameLost() {
	}
	
	public void Screen(String s) {
	}
}
