package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : View.java
//  @ Date : 2020. 05. 05.
//  @ Author : 
//
//


import java.awt.*;
import java.util.ArrayList;
import java.util.List;

import javax.swing.*;

public class View {
	private JFrame frame;
	private JPanel jatekPanel;
	private JPanel jegmezoPanel;
	private List<JComboBox<Object>> taskak=new ArrayList<JComboBox<Object>>();
	private JComboBox<Object> aktTaska;
	private JPanel iranyPanel;
	private JPanel taskaPanel;
	private JButton HasznalButton;
	private JButton FelveszButton;
	private JButton KepessegButton;
	private JButton BalraButton;
	private JButton JobbraButton;
	private JButton LepButton;
	private JButton korvegeButton;
	private JLabel testho;
	private JLabel munka;
	private List<Drawable> drawable=new ArrayList<Drawable>();
	private Controller controller;
	Menu menu;
	/**
	 * @param c controller
	 * @param m menu
	 */
	public View(Controller c, Menu m) {
		controller=c; menu=m;
		inicializalas();
		
	}
	/**
	 * komponensek létrehozása
	 */
	public void inicializalas() {
		munka=new JLabel();
		testho=new JLabel();
		munka.setText("Játékos munkái:");
		testho.setText("Játékos testhõje:");
		setButtons();
		setPanels();
		frame=new JFrame("Jég-veled!");
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);			
	    frame.setPreferredSize(new Dimension(1200, 600));																						
	    frame.setLocationRelativeTo(null);
	    frame.setLayout(new BorderLayout());
	    
	    frame.add(BorderLayout.CENTER, jegmezoPanel);
		frame.add(BorderLayout.EAST, iranyPanel);
		frame.add(BorderLayout.NORTH, jatekPanel);
		frame.add(BorderLayout.WEST, taskaPanel);
		
		frame.setResizable(false);										
		frame.setVisible(true);
		frame.pack();
	    
	}
	
	
	
	
	/**
	 * @param d drawable, kirajzolandó objektum hozzáadás
	 */
	public void addDrawable(Drawable d) {
		drawable.add(d);
	}
	
	/**
	 * képernyõ újra rajzol
	 */
	public void drawAll() {
		jegmezoPanel.repaint();
		iranyPanel.repaint();
		jatekPanel.repaint();
		taskaPanel.repaint();
	}
	
	/**
	 * gombok létrehozása
	 */
	public void setButtons() {
		HasznalButton=new JButton("Tárgy Használ");
		HasznalButton.addActionListener(controller.new TargyActionListener(aktTaska));
		FelveszButton=new JButton("Felvesz");
		FelveszButton.addActionListener(controller.new TargyActionListener(aktTaska));
		KepessegButton=new JButton("Képesség Használ");
		KepessegButton.addActionListener(controller.new GombokActionListener());
		BalraButton=new JButton("Bal");
		BalraButton.addActionListener(controller.new GombokActionListener());
		JobbraButton=new JButton("Jobb");
		JobbraButton.addActionListener(controller.new GombokActionListener());
		LepButton=new JButton("Lép");
		LepButton.addActionListener(controller.new GombokActionListener());
		korvegeButton=new JButton("Jöhet a következõ");
		korvegeButton.addActionListener(controller.new GombokActionListener());
		
	}
	
	/**
	 * panelek létrehozása
	 */
	public void setPanels() {
		jatekPanel=new JPanel();
		jatekPanel.setPreferredSize(new Dimension(900,100));
		jegmezoPanel=new JPanel() {
			public void paintComponent(Graphics g) {
				for(int i=0;i<drawable.size();i++)
					drawable.get(i).draw((Graphics2D)g);
			}
		};
		jegmezoPanel.setPreferredSize(new Dimension(900,500));
		iranyPanel=new JPanel();
		iranyPanel.setPreferredSize(new Dimension(150,500));
		taskaPanel=new JPanel();
		taskaPanel.setPreferredSize(new Dimension(150,500));
		
		iranyPanel.add(FelveszButton);
		iranyPanel.add(KepessegButton);
		iranyPanel.add(JobbraButton);
		iranyPanel.add(BalraButton);
		iranyPanel.add(LepButton);
		iranyPanel.add(korvegeButton);
		
		//taskaPanel.add(aktTaska);
		taskaPanel.add(HasznalButton);
		
		jatekPanel.add(testho);
		jatekPanel.add(munka);
		
	}
	
	
	/**
	 * játték vége, nyertünk
	 */
	public void gameWon() {
		frame.dispose();
		menu.GameWon();
	}
	
	/**
	 * játék vége, vesztettünk
	 */
	public void gameLost() {
		frame.dispose();
		menu.GameLost();
	}
	
	
	/**
	 * @param j új táska felvétele
	 */
	public void AddTaska(JComboBox<Object> j) {
		taskak.add(j);
	}
	/**
	 * @param idx jelenlegi játékoshoz tartozó táska
	 */
	public void setAktTaska(int idx) {
		aktTaska=taskak.get(idx);
	}
	/**
	 * @return jelenleg beállított táska
	 */
	JComboBox<Object> getAktTaska() {
		return aktTaska;
	}
	/**
	 * @return az összes játékos táskája
	 */
	List<JComboBox<Object>> getTaskak() {
		return taskak;
	}
	/**
	 * @param d amit már nem kell kirajzolni
	 * drawable objektum eltávolítása, nem rajzoljuk ki többé
	 */
	public void eltavolitDrawable(Drawable d) {
		drawable.remove(d);
	}
	
	/**
	 * @param n aktuális játékos testhõje
	 * kiírandó testhõ, az aktuális játékos testhõje
	 */
	public void setTestho(int n) {
		testho.setText("Játékos Testhõje: "+n);
	}
	/**
	 * @param n munkadb
	 * aktuális játékos munkái kiírása
	 */
	public void setMunka(int n) {
		munka.setText("Játékos Munkái: "+n);
	}
	
	
}
