package Jegmezo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Visitor.java
//  @ Date : 25/03/2020
//  @ Author : 
//
//




public interface Visitor
{
	/**
	 * Elvégzi az ásóval a leszármazottakban specifikált tevékenységet
	 * @param a - Az ásó, amit használunk
	 * @param j - A játékos, aki hasznája az ásót
	 */
	public void visit(Aso a, Jatekos j);
	
	/**
	 * Elvégzi a kötéllel a leszármazottakban specifikált tevékenységet
	 * @param k - A kötél, amit használunk
	 * @param j - A játékos, aki hasznája a kötélt
	 */
	public void visit(Kotel k, Jatekos j);
	
	/**
	 * Elvégzi a búvárruhával a leszármazottakban specifikált tevékenységet
	 * @param b - A búvárruha, amit használunk
	 * @param j - A játékos, aki hasznája a búvárruhát
	 */
	public void visit(Buvarruha b, Jatekos j);
	
	/**
	 * Elvégzi az élellemmel a leszármazottakban specifikált tevékenységet
	 * @param e - Az élelem, amit használunk
	 * @param j - A játékos, aki hasznája az élelmet
	 */
	public void visit(Elelem e, Jatekos j);
	
	/**
	 * Elvégzi a jelzõpisztollyal a leszármazottakban specifikált tevékenységet
	 * @param jp - A jelzõpisztoly, amit használunk
	 * @param j - A játékos, aki hasznája a jelzõpisztolyt
	 */
	public void visit(Jelzopisztoly jp, Jatekos j);
}
